# Settings to deploy on Netlify

[functions]
  directory = "functions"

[build]
  publish = "public"
  functions = "dist"
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
  
[[redirects]]
  from = "/"
  to = "/.netlify/functions/index"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/tags"
  to = "/.netlify/functions/tags-get"
  status = 200
  force = true

[[redirects]]
  from = "/photos"
  to = "/.netlify/functions/photos-get"
  status = 200
  force = true

[[redirects]]
  from = "/photos/:id"
  to = "/.netlify/functions/photos-id"
  status = 200
  force = true

[[redirects]]
  from = "/photos/:id/comments"
  to = "/.netlify/functions/photos-id-comments-handler"
  status = 200
  force = true