[functions]
  directory = "functions"

[build]
  publish = "public"
  functions = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/tags"
  to = "/.netlify.app/functions/tags-get"
  status = 200
  method = "GET"

[[redirects]]
  from = "/api/photos"
  to = "/.netlify.app/functions/photos-get"
  status = 200
  method = "GET"

[[redirects]]
  from = "/api/photos/:id"
  to = "/.netlify.app/functions/photos-id"
  status = 200
  method = "GET"

[[redirects]]
  from = "/api/photos/:id/comments"
  to = "/.netlify.app/functions/photos-id-comments-get"
  status = 200
  method = "GET"

[[redirects]]
  from = "/api/photos/:id/comments"
  to = "/.netlify.app/functions/photos-id-comments-post"
  status = 200
  method = "POST"