[functions]
  directory = "functions"

[build]
  publish = "public"
  functions = "dist"
  command = "npm run build"

[[edge_functions]]
  path = "/tags"
  function = "/tags-get"

[[edge_functions]]
  path = "/photos"
  function = "/photos-get"

[[edge_functions]]
  path = "/photos/:id"
  function = "/photos-id"

[[edge_functions]]
  path = "/photos/:id/comments"
  function = "/photos-id-comments-get"

[[edge_functions]]
  path = "/photos/:id/comments"
  function = "/photos-id-comments-post"
  method = "POST"