[functions]
  directory = "functions"

[build]
  publish = "public"
  functions = "dist"
  command = "npm run build"

[[redirects]]
  from = "/tags"
  to = "/tags-get"
  status = 200
  method = "GET"

[[redirects]]
  from = "/photos"
  to = "/photos-get"
  status = 200
  method = "GET"

[[redirects]]
  from = "/photos/:id"
  to = "/photos-id"
  status = 200
  method = "GET"

[[redirects]]
  from = "/photos/:id/comments"
  to = "/photos-id-comments-get"
  status = 200
  method = "GET"

[[redirects]]
  from = "/photos/:id/comments"
  to = "/photos-id-comments-post"
  status = 200
  method = "POST"