[functions]
  directory = "functions"

[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/tags"
  to = "/.netlify/functions/tags-get"
  status = 200
  methods = ["GET"]

[[redirects]]
  from = "/photos"
  to = "/.netlify/functions/photos-get"
  status = 200
  methods = ["GET"]

[[redirects]]
  from = "/photos/:id"
  to = "/.netlify/functions/photos-[id]"
  status = 200
  methods = ["GET"]

[[redirects]]
  from = "/photos/:id/comments"
  to = "/.netlify/functions/photos-[id]-comments-get"
  status = 200
  methods = ["GET"]

[[redirects]]
  from = "/photos/:id/comments"
  to = "/.netlify/functions/photos-[id]-comments-post"
  status = 200
  methods = ["POST"]