[functions]
  directory = "functions"

[build]
  publish = "public"
  functions = "dist"
  command = "npm run build"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/index"
  status = 200
  force = true

[[redirects]]
  from = "/tags"
  to = "/.netlify/functions/tags-get"
  status = 200
  force = true

[[redirects]]
  from = "/photos"
  to = "/.netlify/functions/photos-get"
  status = 200
  force = true

[[redirects]]
  from = "/photos/:id"
  to = "/.netlify/functions/photos-id"
  status = 200
  force = true

[[redirects]]
  from = "/photos/:id/comments"
  to = "/.netlify/functions/photos-id-comments-get"
  status = 200
  force = true

[[redirects]]
  from = "/photos/:id/comments"
  to = "/.netlify/functions/photos-id-comments-post"
  method = "POST"
  status = 200
  force = true